CREATE TABLE addresses (
	id BIGSERIAL PRIMARY KEY,
	street VARCHAR(255) NOT NULL,
	city VARCHAR(255) NOT NULL,
	zip VARCHAR(255) NOT NULL,
	state VARCHAR(255) NOT NULL,
	user_id BIGINT REFERENCES users(id)
);
